### PR TITLE
Remove spacing between last block and footer

### PR DESCRIPTION
**Pull request by dwaxweiler**

### CODE REVIEW

**Comment by lutoma** [comment]
Hmm. I think that CSS was added to make the footer always stick to the bottom of the page. Because now when I go to a short content page, the footer ends up in the middle of the screen again. I wonder if there's a good way to get both, if not we should just merge this.

**Comment by dwaxweiler** [comment]
True! I have looked into it again. It is not possible to achieve it with CSS only as our footer is responsive. However, it would work with some JS although it would look ugly when JS is disabled (users of NoScript). Therefore, I am no big fan of it. What do you think?

**Comment by PeterTheOne** [comment]
Setting `body { padding-bottom: }` to the current footer size on load and resize in js should do the trick. Setting padding-bottom to different heights with media-queries could also help, but you can't really predict the height..

**Comment by lutoma** [comment]
Hmm. I guess this is good enough for now, as we don't have any pages that are short enough to trigger the issue anyway. Except maybe on some absurdly wide screen ratios.

**Pull request merged**
