### PR TITLE
add copyfighters position paper to resources

### LINKED ISSUE #45: Add copyfighters position paper to resources

### PR DESCRIPTION
**Pull request by PeterTheOne**
fix #45

### CODE REVIEW

**Comment by PeterTheOne** [comment]
A redirect from the old wordpress link to this file in `static/docs/copyfighters.pdf` would also be nice..

**Comment by dwaxweiler** [comment]
What about adding it to the new resources page that is in the pipe? See #37

**Comment by PeterTheOne** [comment]
@dwaxweiler Or both? Feel free to do what you think is right ;)

**Comment by dwaxweiler** [comment]
@PeterTheOne Please have a look where it fits most and update your request as there is a conflict now.

**Comment by dwaxweiler** [comment]
@PeterTheOne I think that it is a good idea to add it there. Could you just fix the conflict? The file name has changed. The old path to the file is `https://copyfighters.eu/wp-content/uploads/2017/06/copyfighters.pdf`. Does a `.htaccess` file work?

**Comment by PeterTheOne** [comment]
Local git didn't have any conflicts.. ^^ Should be good to merge now.

**Comment by dwaxweiler** [comment]
It looks good! Do you want to try to get the redirect done too?

**Pull request merged**
